// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx5mQqj70uZWYZV0_L2tBsC2dod2ujrAU',
    appId: '1:674741129487:web:ea1aba8ff57bee8d336e7a',
    messagingSenderId: '674741129487',
    projectId: 'soln-no-poverty',
    authDomain: 'soln-no-poverty.firebaseapp.com',
    databaseURL: 'https://soln-no-poverty-default-rtdb.firebaseio.com',
    storageBucket: 'soln-no-poverty.appspot.com',
    measurementId: 'G-D0WME24WNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBlTJYrAlcoxcwCw8YvkpPRLsXma2wRW4',
    appId: '1:674741129487:android:422141e9320e14d4336e7a',
    messagingSenderId: '674741129487',
    projectId: 'soln-no-poverty',
    databaseURL: 'https://soln-no-poverty-default-rtdb.firebaseio.com',
    storageBucket: 'soln-no-poverty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdKLHqi_T7ZoSQ97tcc3roqQqsCAglfsI',
    appId: '1:674741129487:ios:2ba3d61dd3200aef336e7a',
    messagingSenderId: '674741129487',
    projectId: 'soln-no-poverty',
    databaseURL: 'https://soln-no-poverty-default-rtdb.firebaseio.com',
    storageBucket: 'soln-no-poverty.appspot.com',
    androidClientId: '674741129487-6eme2787fsqrhjclqs7d8nr1legn605e.apps.googleusercontent.com',
    iosClientId: '674741129487-8o5bifin0e820i4lfgeof6u49s4r38te.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdKLHqi_T7ZoSQ97tcc3roqQqsCAglfsI',
    appId: '1:674741129487:ios:2ba3d61dd3200aef336e7a',
    messagingSenderId: '674741129487',
    projectId: 'soln-no-poverty',
    databaseURL: 'https://soln-no-poverty-default-rtdb.firebaseio.com',
    storageBucket: 'soln-no-poverty.appspot.com',
    androidClientId: '674741129487-6eme2787fsqrhjclqs7d8nr1legn605e.apps.googleusercontent.com',
    iosClientId: '674741129487-8o5bifin0e820i4lfgeof6u49s4r38te.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
